const STORY_OPTIONS = 
[
{name:	'UserTour'	,script:	UserTour	,under_writable:	false	,cleartext_filename:	''},
{name:	'Kunugi'	,script:	Kunugi	,under_writable:	false	,cleartext_filename:	''},
{name:	'Minda'	,script:	Minda	,under_writable:	false	,cleartext_filename:	'Minda'},
{name:	'Minda2'	,script:	Minda2	,under_writable:	false	,cleartext_filename:	'Minda2'},
{name:	'Inome'	,script:	Inome	,under_writable:	false	,cleartext_filename:	'Inome'},
{name:	'Sakuma'	,script:	Sakuma	,under_writable:	false	,cleartext_filename:	'Sakuma'},
{name:	'Sachi'	,script:	Sachi	,under_writable:	false	,cleartext_filename:	'Sachi'},
{name:	'Baruru'	,script:	Baruru	,under_writable:	false	,cleartext_filename:	'Baruru'},
{name:	'Fumi'	,script:	Fumi	,under_writable:	false	,cleartext_filename:	'Fumi'},
{name:	'Suihoun'	,script:	Suihoun	,under_writable:	true	,cleartext_filename:	"Suihoun"},
{name:	'Ippu'	,script:	Ippu	,under_writable:	false	,cleartext_filename:	'Ippu'},
{name:	'Yoshine'	,script:	Yoshine	,under_writable:	false	,cleartext_filename:	'Yoshine'},
{name:	'Hitami'	,script:	Hitami	,under_writable:	true	,cleartext_filename:	''},
{name:	'Inome2'	,script:	Inome2	,under_writable:	false	,cleartext_filename:	''},
{name:	'Minda3'	,script:	Minda3	,under_writable:	true	,cleartext_filename:	''},
{name:	'Inome3'	,script:	Inome3	,under_writable:	true	,cleartext_filename:	''},
{name:	'Kurokasa'	,script:	Kurokasa	,under_writable:	false	,cleartext_filename:	''},
{name:	'Hitami2'	,script:	Hitami2	,under_writable:	true	,cleartext_filename:	''},
{name:	'Minda4'	,script:	Minda4	,under_writable:	false	,cleartext_filename:	''},
{name:	'Minda5_1'	,script:	Minda5_1	,under_writable:	false	,cleartext_filename:	''},
{name:	'Minda5_2'	,script:	Minda5_2	,under_writable:	false	,cleartext_filename:	''},
{name:	'Umiao'	,script:	Umiao	,under_writable:	true	,cleartext_filename:	''},
{name:	'Yoshine2'	,script:	Yoshine2	,under_writable:	true	,cleartext_filename:	''},
{name:	'Baseru'	,script:	Baseru	,under_writable:	true	,cleartext_filename:	''},
{name:	'Akisato'	,script:	Akisato	,under_writable:	true	,cleartext_filename:	''},
{name:	'Paripero'	,script:	Paripero	,under_writable:	true	,cleartext_filename:	''},
{name:	'Gebu'	,script:	Gebu	,under_writable:	true	,cleartext_filename:	''},
{name:	'Gerufaru'	,script:	Gerufaru	,under_writable:	true	,cleartext_filename:	''},
{name:	'Goeibara'	,script:	Goeibara	,under_writable:	false	,cleartext_filename:	''},
{name:	'Uzinos'	,script:	Uzinos	,under_writable:	false	,cleartext_filename:	''},
{name:	'Seri'	,script:	Seri	,under_writable:	false	,cleartext_filename:	''},
{name:	'Meiju'	,script:	Meiju	,under_writable:	false	,cleartext_filename:	''},
{name:	'Utagemaru'	,script:	Utagemaru	,under_writable:	true	,cleartext_filename:	''},
{name:	'Habaic'	,script:	Habaic	,under_writable:	true	,cleartext_filename:	''},
{name:	'RNakia'	,script:	RNakia	,under_writable:	true	,cleartext_filename:	''},
{name:	'Nitori'	,script:	Nitori	,under_writable:	true	,cleartext_filename:	''},
{name:	'Mitsuyoshi'	,script:	Mitsuyoshi	,under_writable:	true	,cleartext_filename:	''},
{name:	'Kazasaki'	,script:	Kazasaki	,under_writable:	false	,cleartext_filename:	''},
{name:	'Kazasaki2'	,script:	Kazasaki2	,under_writable:	false	,cleartext_filename:	''},
{name:	'Tochino'	,script:	Tochino	,under_writable:	false	,cleartext_filename:	''},
{name:	'Tochino2'	,script:	Tochino2	,under_writable:	false	,cleartext_filename:	''},


];

